name: auto-update-workflow
on: 
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.7'
            cache: 'pip'
      - run: sudo apt install libgirepository1.0-dev
      - run: pip install -r requirements.txt
        working-directory: ./auto-update
      - run: python3 auto-update.py
        working-directory: ./auto-update
      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:
            add: 'public/.'
            push: true
